export const constants = {
    FETCH_ALL_INITIATED: 'FETCH_ALL_INITIATED',
    FETCH_ALL_FULFILLED: 'FETCH_ALL_FULFILLED',
    FETCH_ALL_REJECTED: 'FETCH_ALL_FULFILLED',
    SHOW_SEARCH_RESULTS: 'SHOW_SEARCH_RESULTS',
    LOGIN_INITIATED: 'LOGIN_INITIATED',
    LOGIN_FULFILLED: 'LOGIN_FULFILLED',
    LOGIN_ERROR: 'LOGIN_ERROR',
    USERNAME_CHANGED: 'USERNAME_CHANGED',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED'
};