export const constants = {
    FETCH_ALL_INITIATED: 'FETCH_ALL_INITIATED',
    FETCH_ALL_FULFILLED: 'FETCH_ALL_FULFILLED',
    FETCH_ALL_REJECTED: 'FETCH_ALL_FULFILLED',
    LOGIN_INITIATED: 'LOGIN_INITIATED',
    LOGIN_FULFILLED: 'LOGIN_FULFILLED',
    LOGIN_ERROR: 'LOGIN_ERROR'
};